enum EventKeys {
  PreloaderLoaded = 'preloader-loaded',
  LoadCharacter = 'load-character',
  CharacterLoaded = 'character-loaded',
  GoToEnter = 'go-to-enter',
  GoToHome = 'go-to-home',
  HomeLoaded = 'home-loaded',
  GoToStore = 'go-to-store',
  GoToChooseCharacter = 'go-to-choose-character',
  GoToGame = 'go-to-game',
  GameLoaded = 'game-loaded',
  PauseGame = 'pause-game',
  ResumeGame = 'resume-game',
  CloseGame = 'close-game',
  GoToGameOver = 'go-to-game-over',
  GameOverLoaded = 'game-over-loaded',
  CloseGameOver = 'close-game-over',
  UpdateScore = 'update-score',
  UpdateEndScore = 'update-end-score',
  UpdateHighScore = 'update-high-score',
  Run = 'run',
  ChangeVolume = 'change-volume'
}
export default EventKeys;
